package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Long addressId;
	private Long donorId;
	private String line1;
	private String line2;
	private String city;
	private String state;
	private String zipcode;
	private String majorIntersection;
	private String subdivision;
	private String streetSuffix;
	private String structureType;
	private String unit;
	private String building;
	private String floor;
	private String elevatorFlag;
	private String gatedFlag;
	private String gateInstructions;
	private String createdBy;
	private String lastUpdatedBy;
	private String lastUpdatedDate;
	private String creationDate;

	public Address() {
	}

	public Address(String line1, String city, String state, String zipcode,
			String majorIntersection) {
		this.line1 = line1;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.majorIntersection = majorIntersection;
	}

	public Address(Long donorId, String line1, String line2, String city,
			String state, String zipcode, String majorIntersection,
			String subdivision, String streetSuffix, String structureType,
			String unit, String building, String floor, String elevatorFlag,
			String gatedFlag, String gateInstructions, String createdBy,
			String lastUpdatedBy, String lastUpdatedDate, String creationDate) {
		this.donorId = donorId;
		this.line1 = line1;
		this.line2 = line2;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.majorIntersection = majorIntersection;
		this.subdivision = subdivision;
		this.streetSuffix = streetSuffix;
		this.structureType = structureType;
		this.unit = unit;
		this.building = building;
		this.floor = floor;
		this.elevatorFlag = elevatorFlag;
		this.gatedFlag = gatedFlag;
		this.gateInstructions = gateInstructions;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.creationDate = creationDate;
	}

	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public Long getDonorId() {
		return this.donorId;
	}

	public void setDonorId(Long donorId) {
		this.donorId = donorId;
	}

	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getMajorIntersection() {
		return this.majorIntersection;
	}

	public void setMajorIntersection(String majorIntersection) {
		this.majorIntersection = majorIntersection;
	}

	public String getSubdivision() {
		return this.subdivision;
	}

	public void setSubdivision(String subdivision) {
		this.subdivision = subdivision;
	}

	public String getStreetSuffix() {
		return this.streetSuffix;
	}

	public void setStreetSuffix(String streetSuffix) {
		this.streetSuffix = streetSuffix;
	}

	public String getStructureType() {
		return this.structureType;
	}

	public void setStructureType(String structureType) {
		this.structureType = structureType;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getBuilding() {
		return this.building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public String getElevatorFlag() {
		return this.elevatorFlag;
	}

	public void setElevatorFlag(String elevatorFlag) {
		this.elevatorFlag = elevatorFlag;
	}

	public String getGatedFlag() {
		return this.gatedFlag;
	}

	public void setGatedFlag(String gatedFlag) {
		this.gatedFlag = gatedFlag;
	}

	public String getGateInstructions() {
		return this.gateInstructions;
	}

	public void setGateInstructions(String gateInstructions) {
		this.gateInstructions = gateInstructions;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

}
