package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * CallLog generated by hbm2java
 */
public class CallLog implements java.io.Serializable {

	private Long callLogId;
	private String callType;
	private String source;
	private String callDate;
	private String callAgent;
	private String farmBase;

	public CallLog() {
	}

	public CallLog(String callType, String source, String callDate,
			String callAgent, String farmBase) {
		this.callType = callType;
		this.source = source;
		this.callDate = callDate;
		this.callAgent = callAgent;
		this.farmBase = farmBase;
	}

	public Long getCallLogId() {
		return this.callLogId;
	}

	public void setCallLogId(Long callLogId) {
		this.callLogId = callLogId;
	}

	public String getCallType() {
		return this.callType;
	}

	public void setCallType(String callType) {
		this.callType = callType;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getCallDate() {
		return this.callDate;
	}

	public void setCallDate(String callDate) {
		this.callDate = callDate;
	}

	public String getCallAgent() {
		return this.callAgent;
	}

	public void setCallAgent(String callAgent) {
		this.callAgent = callAgent;
	}

	public String getFarmBase() {
		return this.farmBase;
	}

	public void setFarmBase(String farmBase) {
		this.farmBase = farmBase;
	}

}
