package com.yada180.sms.domain;

// Generated Sep 18, 2013 1:34:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * CourseRotationHistory generated by hbm2java
 */
public class CourseRotationHistory implements java.io.Serializable {

	private Long courseRotationId;
	private String rotationDate;
	private Integer movedCourse0To1;
	private Integer movedCourse1To2;
	private Integer movedCourse2To3;
	private Integer movedCourse3To4;
	private Integer movedCourse4To5;
	private Integer movedCourse5To6;
	private Integer heldCourse0;
	private Integer heldCourse1;
	private Integer heldCourse2;
	private Integer heldCourse3;
	private Integer heldCourse4;
	private Integer heldCourse5;
	private Integer heldCourse6;
	private Integer graduated;
	private String createdBy;

	public CourseRotationHistory() {
	}

	public CourseRotationHistory(String rotationDate, Integer movedCourse0To1,
			Integer movedCourse1To2, Integer movedCourse2To3,
			Integer movedCourse3To4, Integer movedCourse4To5,
			Integer movedCourse5To6, Integer heldCourse0, Integer heldCourse1,
			Integer heldCourse2, Integer heldCourse3, Integer heldCourse4,
			Integer heldCourse5, Integer heldCourse6, Integer graduated,
			String createdBy) {
		this.rotationDate = rotationDate;
		this.movedCourse0To1 = movedCourse0To1;
		this.movedCourse1To2 = movedCourse1To2;
		this.movedCourse2To3 = movedCourse2To3;
		this.movedCourse3To4 = movedCourse3To4;
		this.movedCourse4To5 = movedCourse4To5;
		this.movedCourse5To6 = movedCourse5To6;
		this.heldCourse0 = heldCourse0;
		this.heldCourse1 = heldCourse1;
		this.heldCourse2 = heldCourse2;
		this.heldCourse3 = heldCourse3;
		this.heldCourse4 = heldCourse4;
		this.heldCourse5 = heldCourse5;
		this.heldCourse6 = heldCourse6;
		this.graduated = graduated;
		this.createdBy = createdBy;
	}

	public Long getCourseRotationId() {
		return this.courseRotationId;
	}

	public void setCourseRotationId(Long courseRotationId) {
		this.courseRotationId = courseRotationId;
	}

	public String getRotationDate() {
		return this.rotationDate;
	}

	public void setRotationDate(String rotationDate) {
		this.rotationDate = rotationDate;
	}

	public Integer getMovedCourse0To1() {
		return this.movedCourse0To1;
	}

	public void setMovedCourse0To1(Integer movedCourse0To1) {
		this.movedCourse0To1 = movedCourse0To1;
	}

	public Integer getMovedCourse1To2() {
		return this.movedCourse1To2;
	}

	public void setMovedCourse1To2(Integer movedCourse1To2) {
		this.movedCourse1To2 = movedCourse1To2;
	}

	public Integer getMovedCourse2To3() {
		return this.movedCourse2To3;
	}

	public void setMovedCourse2To3(Integer movedCourse2To3) {
		this.movedCourse2To3 = movedCourse2To3;
	}

	public Integer getMovedCourse3To4() {
		return this.movedCourse3To4;
	}

	public void setMovedCourse3To4(Integer movedCourse3To4) {
		this.movedCourse3To4 = movedCourse3To4;
	}

	public Integer getMovedCourse4To5() {
		return this.movedCourse4To5;
	}

	public void setMovedCourse4To5(Integer movedCourse4To5) {
		this.movedCourse4To5 = movedCourse4To5;
	}

	public Integer getMovedCourse5To6() {
		return this.movedCourse5To6;
	}

	public void setMovedCourse5To6(Integer movedCourse5To6) {
		this.movedCourse5To6 = movedCourse5To6;
	}

	public Integer getHeldCourse0() {
		return this.heldCourse0;
	}

	public void setHeldCourse0(Integer heldCourse0) {
		this.heldCourse0 = heldCourse0;
	}

	public Integer getHeldCourse1() {
		return this.heldCourse1;
	}

	public void setHeldCourse1(Integer heldCourse1) {
		this.heldCourse1 = heldCourse1;
	}

	public Integer getHeldCourse2() {
		return this.heldCourse2;
	}

	public void setHeldCourse2(Integer heldCourse2) {
		this.heldCourse2 = heldCourse2;
	}

	public Integer getHeldCourse3() {
		return this.heldCourse3;
	}

	public void setHeldCourse3(Integer heldCourse3) {
		this.heldCourse3 = heldCourse3;
	}

	public Integer getHeldCourse4() {
		return this.heldCourse4;
	}

	public void setHeldCourse4(Integer heldCourse4) {
		this.heldCourse4 = heldCourse4;
	}

	public Integer getHeldCourse5() {
		return this.heldCourse5;
	}

	public void setHeldCourse5(Integer heldCourse5) {
		this.heldCourse5 = heldCourse5;
	}

	public Integer getHeldCourse6() {
		return this.heldCourse6;
	}

	public void setHeldCourse6(Integer heldCourse6) {
		this.heldCourse6 = heldCourse6;
	}

	public Integer getGraduated() {
		return this.graduated;
	}

	public void setGraduated(Integer graduated) {
		this.graduated = graduated;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
