package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtDepartment generated by hbm2java
 */
public class CwtDepartment implements java.io.Serializable {

	private Long departmentId;
	private String farmBase;
	private String creationDate;
	private String createdBy;
	private String title;

	public CwtDepartment() {
	}

	public CwtDepartment(String farmBase, String creationDate,
			String createdBy, String title) {
		this.farmBase = farmBase;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
		this.title = title;
	}

	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	public String getFarmBase() {
		return this.farmBase;
	}

	public void setFarmBase(String farmBase) {
		this.farmBase = farmBase;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
