package com.yada180.sms.domain;

// Generated Sep 18, 2013 1:34:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtJobAssignment generated by hbm2java
 */
public class CwtJobAssignment implements java.io.Serializable {

	private Long jobAssignmentId;
	private Long intakeId;
	private String creationDate;
	private String createdBy;
	private Long jobId;

	public CwtJobAssignment() {
	}

	public CwtJobAssignment(Long intakeId, String creationDate,
			String createdBy, Long jobId) {
		this.intakeId = intakeId;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
		this.jobId = jobId;
	}

	public Long getJobAssignmentId() {
		return this.jobAssignmentId;
	}

	public void setJobAssignmentId(Long jobAssignmentId) {
		this.jobAssignmentId = jobAssignmentId;
	}

	public Long getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(Long intakeId) {
		this.intakeId = intakeId;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

}
