package com.yada180.sms.domain;

// Generated Sep 16, 2013 10:14:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * CwtJobMetric generated by hbm2java
 */
public class CwtJobMetric implements java.io.Serializable {

	private long metricId;
	private Long jobId;

	public CwtJobMetric() {
	}

	public CwtJobMetric(long metricId) {
		this.metricId = metricId;
	}

	public CwtJobMetric(long metricId, Long jobId) {
		this.metricId = metricId;
		this.jobId = jobId;
	}

	public long getMetricId() {
		return this.metricId;
	}

	public void setMetricId(long metricId) {
		this.metricId = metricId;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

}
