package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtJob generated by hbm2java
 */
public class CwtJob implements java.io.Serializable {

	private Long jobId;
	private String title;
	private String description;
	private String createdBy;
	private String creationDate;
	private long departmentId;

	public CwtJob() {
	}

	public CwtJob(long departmentId) {
		this.departmentId = departmentId;
	}

	public CwtJob(String title, String description, String createdBy,
			String creationDate, long departmentId) {
		this.title = title;
		this.description = description;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.departmentId = departmentId;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(long departmentId) {
		this.departmentId = departmentId;
	}

}
