package com.yada180.sms.domain;

// Generated Sep 16, 2013 10:14:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * CwtProgramMetricModules generated by hbm2java
 */
public class CwtProgramMetricModules implements java.io.Serializable {

	private CwtProgramMetricModulesId id;

	public CwtProgramMetricModules() {
	}

	public CwtProgramMetricModules(CwtProgramMetricModulesId id) {
		this.id = id;
	}

	public CwtProgramMetricModulesId getId() {
		return this.id;
	}

	public void setId(CwtProgramMetricModulesId id) {
		this.id = id;
	}

}
