package com.yada180.sms.domain;

// Generated Sep 18, 2013 1:34:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtProgramMetricModulesId generated by hbm2java
 */
public class CwtProgramMetricModulesId implements java.io.Serializable {

	private long metricId;
	private long moduleId;
	private String status;

	public CwtProgramMetricModulesId() {
	}

	public CwtProgramMetricModulesId(long metricId, long moduleId) {
		this.metricId = metricId;
		this.moduleId = moduleId;
	}

	public CwtProgramMetricModulesId(long metricId, long moduleId, String status) {
		this.metricId = metricId;
		this.moduleId = moduleId;
		this.status = status;
	}

	public long getMetricId() {
		return this.metricId;
	}

	public void setMetricId(long metricId) {
		this.metricId = metricId;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CwtProgramMetricModulesId))
			return false;
		CwtProgramMetricModulesId castOther = (CwtProgramMetricModulesId) other;

		return (this.getMetricId() == castOther.getMetricId())
				&& (this.getModuleId() == castOther.getModuleId())
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMetricId();
		result = 37 * result + (int) this.getModuleId();
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
