package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtProgramMetric generated by hbm2java
 */
public class CwtProgramMetric implements java.io.Serializable {

	private Long programMetricId;
	private Long metricId;
	private Long programId;

	public CwtProgramMetric() {
	}

	public CwtProgramMetric(Long metricId, Long programId) {
		this.metricId = metricId;
		this.programId = programId;
	}

	public Long getProgramMetricId() {
		return this.programMetricId;
	}

	public void setProgramMetricId(Long programMetricId) {
		this.programMetricId = programMetricId;
	}

	public Long getMetricId() {
		return this.metricId;
	}

	public void setMetricId(Long metricId) {
		this.metricId = metricId;
	}

	public Long getProgramId() {
		return this.programId;
	}

	public void setProgramId(Long programId) {
		this.programId = programId;
	}

}
