package com.yada180.sms.domain;

// Generated Sep 23, 2013 3:46:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtProgramMetricModules generated by hbm2java
 */
public class CwtProgramMetricModules implements java.io.Serializable {

	private Long programMetricModuleId;
	private long metricId;
	private long moduleId;
	private String status;

	public CwtProgramMetricModules() {
	}

	public CwtProgramMetricModules(long metricId, long moduleId) {
		this.metricId = metricId;
		this.moduleId = moduleId;
	}

	public CwtProgramMetricModules(long metricId, long moduleId, String status) {
		this.metricId = metricId;
		this.moduleId = moduleId;
		this.status = status;
	}

	public Long getProgramMetricModuleId() {
		return this.programMetricModuleId;
	}

	public void setProgramMetricModuleId(Long programMetricModuleId) {
		this.programMetricModuleId = programMetricModuleId;
	}

	public long getMetricId() {
		return this.metricId;
	}

	public void setMetricId(long metricId) {
		this.metricId = metricId;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
