package com.yada180.sms.domain;

// Generated Sep 18, 2013 1:34:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * DailyLimit generated by hbm2java
 */
public class DailyLimit implements java.io.Serializable {

	private Long dailyLimitId;
	private String dispatchDate;
	private int dailyLimit;
	private String updatedBy;
	private String updatedDate;
	private String farmBase;

	public DailyLimit() {
	}

	public DailyLimit(String dispatchDate, int dailyLimit, String updatedBy,
			String updatedDate, String farmBase) {
		this.dispatchDate = dispatchDate;
		this.dailyLimit = dailyLimit;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.farmBase = farmBase;
	}

	public Long getDailyLimitId() {
		return this.dailyLimitId;
	}

	public void setDailyLimitId(Long dailyLimitId) {
		this.dailyLimitId = dailyLimitId;
	}

	public String getDispatchDate() {
		return this.dispatchDate;
	}

	public void setDispatchDate(String dispatchDate) {
		this.dispatchDate = dispatchDate;
	}

	public int getDailyLimit() {
		return this.dailyLimit;
	}

	public void setDailyLimit(int dailyLimit) {
		this.dailyLimit = dailyLimit;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getFarmBase() {
		return this.farmBase;
	}

	public void setFarmBase(String farmBase) {
		this.farmBase = farmBase;
	}

}
