package com.yada180.sms.domain;

// Generated Sep 16, 2013 10:14:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * Donation generated by hbm2java
 */
public class Donation implements java.io.Serializable {

	private Long donationId;
	private long donorId;
	private String confirmationNumber;
	private String dispatchDate;
	private String status;
	private String specialFlag;
	private String callRequirements;
	private String ac;
	private String bedding;
	private String beddingQtyType;
	private String books;
	private String booksQtyType;
	private String clothing;
	private String clothingQtyType;
	private String computer;
	private String desk;
	private String chest;
	private String armoire;
	private String dresser;
	private String mirror;
	private String nightstand;
	private String headboard;
	private String footboard;
	private String rails;
	private String lamp;
	private String lawnFurniture;
	private String mattress;
	private String mattressQtySize;
	private String miscHouseholdItems;
	private String refridgerator;
	private String stove;
	private String recliner;
	private String sofa;
	private String loveseat;
	private String wallUnit;
	private String tables;
	private String chair;
	private String television;
	private String televisionSize;
	private String electronics;
	private String washer;
	private String dryer;
	private String exerciseEquipment;
	private String specialNotes;
	private String creationDate;
	private String createdBy;
	private String lastUpdatedDate;
	private String updatedBy;
	private String farmBase;
	private String tableType;
	private String chairType;
	private String location;
	private String bookcase;
	private String ottoman;

	public Donation() {
	}

	public Donation(long donorId, String farmBase) {
		this.donorId = donorId;
		this.farmBase = farmBase;
	}

	public Donation(long donorId, String confirmationNumber,
			String dispatchDate, String status, String specialFlag,
			String callRequirements, String ac, String bedding,
			String beddingQtyType, String books, String booksQtyType,
			String clothing, String clothingQtyType, String computer,
			String desk, String chest, String armoire, String dresser,
			String mirror, String nightstand, String headboard,
			String footboard, String rails, String lamp, String lawnFurniture,
			String mattress, String mattressQtySize, String miscHouseholdItems,
			String refridgerator, String stove, String recliner, String sofa,
			String loveseat, String wallUnit, String tables, String chair,
			String television, String televisionSize, String electronics,
			String washer, String dryer, String exerciseEquipment,
			String specialNotes, String creationDate, String createdBy,
			String lastUpdatedDate, String updatedBy, String farmBase,
			String tableType, String chairType, String location,
			String bookcase, String ottoman) {
		this.donorId = donorId;
		this.confirmationNumber = confirmationNumber;
		this.dispatchDate = dispatchDate;
		this.status = status;
		this.specialFlag = specialFlag;
		this.callRequirements = callRequirements;
		this.ac = ac;
		this.bedding = bedding;
		this.beddingQtyType = beddingQtyType;
		this.books = books;
		this.booksQtyType = booksQtyType;
		this.clothing = clothing;
		this.clothingQtyType = clothingQtyType;
		this.computer = computer;
		this.desk = desk;
		this.chest = chest;
		this.armoire = armoire;
		this.dresser = dresser;
		this.mirror = mirror;
		this.nightstand = nightstand;
		this.headboard = headboard;
		this.footboard = footboard;
		this.rails = rails;
		this.lamp = lamp;
		this.lawnFurniture = lawnFurniture;
		this.mattress = mattress;
		this.mattressQtySize = mattressQtySize;
		this.miscHouseholdItems = miscHouseholdItems;
		this.refridgerator = refridgerator;
		this.stove = stove;
		this.recliner = recliner;
		this.sofa = sofa;
		this.loveseat = loveseat;
		this.wallUnit = wallUnit;
		this.tables = tables;
		this.chair = chair;
		this.television = television;
		this.televisionSize = televisionSize;
		this.electronics = electronics;
		this.washer = washer;
		this.dryer = dryer;
		this.exerciseEquipment = exerciseEquipment;
		this.specialNotes = specialNotes;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.updatedBy = updatedBy;
		this.farmBase = farmBase;
		this.tableType = tableType;
		this.chairType = chairType;
		this.location = location;
		this.bookcase = bookcase;
		this.ottoman = ottoman;
	}

	public Long getDonationId() {
		return this.donationId;
	}

	public void setDonationId(Long donationId) {
		this.donationId = donationId;
	}

	public long getDonorId() {
		return this.donorId;
	}

	public void setDonorId(long donorId) {
		this.donorId = donorId;
	}

	public String getConfirmationNumber() {
		return this.confirmationNumber;
	}

	public void setConfirmationNumber(String confirmationNumber) {
		this.confirmationNumber = confirmationNumber;
	}

	public String getDispatchDate() {
		return this.dispatchDate;
	}

	public void setDispatchDate(String dispatchDate) {
		this.dispatchDate = dispatchDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getSpecialFlag() {
		return this.specialFlag;
	}

	public void setSpecialFlag(String specialFlag) {
		this.specialFlag = specialFlag;
	}

	public String getCallRequirements() {
		return this.callRequirements;
	}

	public void setCallRequirements(String callRequirements) {
		this.callRequirements = callRequirements;
	}

	public String getAc() {
		return this.ac;
	}

	public void setAc(String ac) {
		this.ac = ac;
	}

	public String getBedding() {
		return this.bedding;
	}

	public void setBedding(String bedding) {
		this.bedding = bedding;
	}

	public String getBeddingQtyType() {
		return this.beddingQtyType;
	}

	public void setBeddingQtyType(String beddingQtyType) {
		this.beddingQtyType = beddingQtyType;
	}

	public String getBooks() {
		return this.books;
	}

	public void setBooks(String books) {
		this.books = books;
	}

	public String getBooksQtyType() {
		return this.booksQtyType;
	}

	public void setBooksQtyType(String booksQtyType) {
		this.booksQtyType = booksQtyType;
	}

	public String getClothing() {
		return this.clothing;
	}

	public void setClothing(String clothing) {
		this.clothing = clothing;
	}

	public String getClothingQtyType() {
		return this.clothingQtyType;
	}

	public void setClothingQtyType(String clothingQtyType) {
		this.clothingQtyType = clothingQtyType;
	}

	public String getComputer() {
		return this.computer;
	}

	public void setComputer(String computer) {
		this.computer = computer;
	}

	public String getDesk() {
		return this.desk;
	}

	public void setDesk(String desk) {
		this.desk = desk;
	}

	public String getChest() {
		return this.chest;
	}

	public void setChest(String chest) {
		this.chest = chest;
	}

	public String getArmoire() {
		return this.armoire;
	}

	public void setArmoire(String armoire) {
		this.armoire = armoire;
	}

	public String getDresser() {
		return this.dresser;
	}

	public void setDresser(String dresser) {
		this.dresser = dresser;
	}

	public String getMirror() {
		return this.mirror;
	}

	public void setMirror(String mirror) {
		this.mirror = mirror;
	}

	public String getNightstand() {
		return this.nightstand;
	}

	public void setNightstand(String nightstand) {
		this.nightstand = nightstand;
	}

	public String getHeadboard() {
		return this.headboard;
	}

	public void setHeadboard(String headboard) {
		this.headboard = headboard;
	}

	public String getFootboard() {
		return this.footboard;
	}

	public void setFootboard(String footboard) {
		this.footboard = footboard;
	}

	public String getRails() {
		return this.rails;
	}

	public void setRails(String rails) {
		this.rails = rails;
	}

	public String getLamp() {
		return this.lamp;
	}

	public void setLamp(String lamp) {
		this.lamp = lamp;
	}

	public String getLawnFurniture() {
		return this.lawnFurniture;
	}

	public void setLawnFurniture(String lawnFurniture) {
		this.lawnFurniture = lawnFurniture;
	}

	public String getMattress() {
		return this.mattress;
	}

	public void setMattress(String mattress) {
		this.mattress = mattress;
	}

	public String getMattressQtySize() {
		return this.mattressQtySize;
	}

	public void setMattressQtySize(String mattressQtySize) {
		this.mattressQtySize = mattressQtySize;
	}

	public String getMiscHouseholdItems() {
		return this.miscHouseholdItems;
	}

	public void setMiscHouseholdItems(String miscHouseholdItems) {
		this.miscHouseholdItems = miscHouseholdItems;
	}

	public String getRefridgerator() {
		return this.refridgerator;
	}

	public void setRefridgerator(String refridgerator) {
		this.refridgerator = refridgerator;
	}

	public String getStove() {
		return this.stove;
	}

	public void setStove(String stove) {
		this.stove = stove;
	}

	public String getRecliner() {
		return this.recliner;
	}

	public void setRecliner(String recliner) {
		this.recliner = recliner;
	}

	public String getSofa() {
		return this.sofa;
	}

	public void setSofa(String sofa) {
		this.sofa = sofa;
	}

	public String getLoveseat() {
		return this.loveseat;
	}

	public void setLoveseat(String loveseat) {
		this.loveseat = loveseat;
	}

	public String getWallUnit() {
		return this.wallUnit;
	}

	public void setWallUnit(String wallUnit) {
		this.wallUnit = wallUnit;
	}

	public String getTables() {
		return this.tables;
	}

	public void setTables(String tables) {
		this.tables = tables;
	}

	public String getChair() {
		return this.chair;
	}

	public void setChair(String chair) {
		this.chair = chair;
	}

	public String getTelevision() {
		return this.television;
	}

	public void setTelevision(String television) {
		this.television = television;
	}

	public String getTelevisionSize() {
		return this.televisionSize;
	}

	public void setTelevisionSize(String televisionSize) {
		this.televisionSize = televisionSize;
	}

	public String getElectronics() {
		return this.electronics;
	}

	public void setElectronics(String electronics) {
		this.electronics = electronics;
	}

	public String getWasher() {
		return this.washer;
	}

	public void setWasher(String washer) {
		this.washer = washer;
	}

	public String getDryer() {
		return this.dryer;
	}

	public void setDryer(String dryer) {
		this.dryer = dryer;
	}

	public String getExerciseEquipment() {
		return this.exerciseEquipment;
	}

	public void setExerciseEquipment(String exerciseEquipment) {
		this.exerciseEquipment = exerciseEquipment;
	}

	public String getSpecialNotes() {
		return this.specialNotes;
	}

	public void setSpecialNotes(String specialNotes) {
		this.specialNotes = specialNotes;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getFarmBase() {
		return this.farmBase;
	}

	public void setFarmBase(String farmBase) {
		this.farmBase = farmBase;
	}

	public String getTableType() {
		return this.tableType;
	}

	public void setTableType(String tableType) {
		this.tableType = tableType;
	}

	public String getChairType() {
		return this.chairType;
	}

	public void setChairType(String chairType) {
		this.chairType = chairType;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getBookcase() {
		return this.bookcase;
	}

	public void setBookcase(String bookcase) {
		this.bookcase = bookcase;
	}

	public String getOttoman() {
		return this.ottoman;
	}

	public void setOttoman(String ottoman) {
		this.ottoman = ottoman;
	}

}
