package com.yada180.sms.domain;

// Generated Sep 16, 2013 10:14:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * Donor generated by hbm2java
 */
public class Donor implements java.io.Serializable {

	private Long donorId;
	private String lastname;
	private String firstname;
	private String suffix;
	private String contactPhone;
	private String emailAddress;
	private String creationDate;
	private String lastUpdatedDate;
	private String createdBy;
	private String updatedBy;

	public Donor() {
	}

	public Donor(String lastname, String firstname, String contactPhone,
			String emailAddress) {
		this.lastname = lastname;
		this.firstname = firstname;
		this.contactPhone = contactPhone;
		this.emailAddress = emailAddress;
	}

	public Donor(String lastname, String firstname, String suffix,
			String contactPhone, String emailAddress, String creationDate,
			String lastUpdatedDate, String createdBy, String updatedBy) {
		this.lastname = lastname;
		this.firstname = firstname;
		this.suffix = suffix;
		this.contactPhone = contactPhone;
		this.emailAddress = emailAddress;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public Long getDonorId() {
		return this.donorId;
	}

	public void setDonorId(Long donorId) {
		this.donorId = donorId;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
