package com.yada180.sms.domain;

// Generated Sep 16, 2013 10:14:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * IntakeReference generated by hbm2java
 */
public class IntakeReference implements java.io.Serializable {

	private Long intakeReference;
	private long intakeId;
	private String name;
	private String contactPhone;
	private String contactEmail;
	private String yearsKnown;
	private String relationship;

	public IntakeReference() {
	}

	public IntakeReference(long intakeId, String name) {
		this.intakeId = intakeId;
		this.name = name;
	}

	public IntakeReference(long intakeId, String name, String contactPhone,
			String contactEmail, String yearsKnown, String relationship) {
		this.intakeId = intakeId;
		this.name = name;
		this.contactPhone = contactPhone;
		this.contactEmail = contactEmail;
		this.yearsKnown = yearsKnown;
		this.relationship = relationship;
	}

	public Long getIntakeReference() {
		return this.intakeReference;
	}

	public void setIntakeReference(Long intakeReference) {
		this.intakeReference = intakeReference;
	}

	public long getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(long intakeId) {
		this.intakeId = intakeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getYearsKnown() {
		return this.yearsKnown;
	}

	public void setYearsKnown(String yearsKnown) {
		this.yearsKnown = yearsKnown;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

}
