package com.yada180.sms.domain;

// Generated Sep 18, 2013 1:34:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntakeCourseEnrollment generated by hbm2java
 */
public class IntakeCourseEnrollment implements java.io.Serializable {

	private long intakeCourseEnrollmentId;
	private long courseId;
	private long intakeId;
	private String status;
	private String creationDate;
	private String createdBy;

	public IntakeCourseEnrollment() {
	}

	public IntakeCourseEnrollment(long intakeCourseEnrollmentId, long courseId,
			long intakeId, String status) {
		this.intakeCourseEnrollmentId = intakeCourseEnrollmentId;
		this.courseId = courseId;
		this.intakeId = intakeId;
		this.status = status;
	}

	public IntakeCourseEnrollment(long intakeCourseEnrollmentId, long courseId,
			long intakeId, String status, String creationDate, String createdBy) {
		this.intakeCourseEnrollmentId = intakeCourseEnrollmentId;
		this.courseId = courseId;
		this.intakeId = intakeId;
		this.status = status;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
	}

	public long getIntakeCourseEnrollmentId() {
		return this.intakeCourseEnrollmentId;
	}

	public void setIntakeCourseEnrollmentId(long intakeCourseEnrollmentId) {
		this.intakeCourseEnrollmentId = intakeCourseEnrollmentId;
	}

	public long getCourseId() {
		return this.courseId;
	}

	public void setCourseId(long courseId) {
		this.courseId = courseId;
	}

	public long getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(long intakeId) {
		this.intakeId = intakeId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
