package com.yada180.sms.domain;

// Generated Sep 18, 2013 1:34:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntakeRecordEntry generated by hbm2java
 */
public class IntakeRecordEntry implements java.io.Serializable {

	private int intakeRecordEntryId;
	private long intakeId;
	private String recordType;
	private String description;
	private String creationDate;
	private String createdBy;

	public IntakeRecordEntry() {
	}

	public IntakeRecordEntry(int intakeRecordEntryId, long intakeId) {
		this.intakeRecordEntryId = intakeRecordEntryId;
		this.intakeId = intakeId;
	}

	public IntakeRecordEntry(int intakeRecordEntryId, long intakeId,
			String recordType, String description, String creationDate,
			String createdBy) {
		this.intakeRecordEntryId = intakeRecordEntryId;
		this.intakeId = intakeId;
		this.recordType = recordType;
		this.description = description;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
	}

	public int getIntakeRecordEntryId() {
		return this.intakeRecordEntryId;
	}

	public void setIntakeRecordEntryId(int intakeRecordEntryId) {
		this.intakeRecordEntryId = intakeRecordEntryId;
	}

	public long getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(long intakeId) {
		this.intakeId = intakeId;
	}

	public String getRecordType() {
		return this.recordType;
	}

	public void setRecordType(String recordType) {
		this.recordType = recordType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
