package com.yada180.sms.domain;

// Generated Sep 19, 2013 3:10:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Intake generated by hbm2java
 */
public class Intake implements java.io.Serializable {

	private Integer intakeId;
	private String lastname;
	private String firstname;
	private String mi;
	private String suffix;
	private String address;
	private String city;
	private String state;
	private String zipcode;
	private String dob;
	private String ssn;
	private String ssnCardFlag;
	private String age;
	private String height;
	private String weight;
	private String ethnicity;
	private String hairColor;
	private String eyeColor;
	private String maritalStatus;
	private String educationLevel;
	private String graduateFlag;
	private String transcriptsFlag;
	private String englishSpeakingFlag;
	private String englishReadingFlag;
	private String homeLocation;
	private String referredBy;
	private String referredByPhone;
	private String emergencyContact;
	private String emergencyPhone;
	private String emergencryRelationship;
	private String motherLivingFlag;
	private String fatherLivingFlag;
	private String brothers;
	private String sisters;
	private String children;
	private String veteranStatus;
	private String branchOfService;
	private String rank;
	private String lengthOfService;
	private String dlFlag;
	private String dlNumber;
	private String dlState;
	private String dlExpDate;
	private String stateIdFlag;
	private String stateIdState;
	private String stateIdExpDate;
	private String governmentBenefitsFlag;
	private String religion;
	private String religiousExperience;
	private String alcoholLastUsed;
	private String cocaineLastUsed;
	private String marijuanaLastUsed;
	private String oxycodoneLastUsed;
	private String speedLastUsed;
	private String heroinLastUsed;
	private String xanaxLastUsed;
	private String otherLastUsed;
	private String alcoholYearsUsed;
	private String cocaineYearsUsed;
	private String marijuanaYearsUsed;
	private String oxycodoneYearsUsed;
	private String speedYearsUsed;
	private String heroinYearsUsed;
	private String xanaxYearsUsed;
	private String otherYearsUsed;
	private String sober1Year;
	private String sober3Years;
	private String usagePattern;
	private String quantityPerWeek;
	private String quantity2Years;
	private String usageLosses;
	private String physicalEffects;
	private String aaFlag;
	private String naFlag;
	private String prevFfFlag;
	private String prevFfYear;
	private String prevFfOther;
	private String currentHealth;
	private String medicationFlag;
	private String medicationSupplyFlag;
	private String medicationNeedFlag;
	private String medicationDetails;
	private String medicationRefillDetails;
	private String doctorApptFlag;
	private String doctorApptDetails;
	private String eyewearFlag;
	private String eyewearUsage;
	private String homelessTime;
	private String homelessReason;
	private String homelessHowOften;
	private String industrialInjuryFlag;
	private String industrialInjuryDate;
	private String industrialInjuryReason;
	private String industrialInjuryLocation;
	private String industrialInjuryEmployer;
	private String industrialInjuryClaimStatus;
	private String disabilityFlag;
	private String disabilityDetails;
	private String disabilityExaminationDate;
	private String disabilityPhysician;
	private String disabilityPhysicianAddress;
	private String herniaSide;
	private String herniaOperationFlag;
	private String herniaDetails;
	private String lawsuitFlag;
	private String currentLawsuitFlag;
	private String lawsuitDetails;
	private String currentLawsuitDetails;
	private String felonyFlag;
	private String sexualOffenseFlag;
	private String felonyDetails;
	private String sexualOffenseQty;
	private String sexualOffenseDetails;
	private String probationFlag;
	private String probationCounty;
	private String probationOfficer;
	private String probationOfficerPhone;
	private String probationApptFlag;
	private String probationApptDetails;
	private String incomeAmount;
	private String incomeSource;
	private String incomeWeeklyFlag;
	private String incomeMonthlyFlag;
	private String applicationStatus;
	private String applicationSignature;
	private String intakeCounselorSignature;
	private String directorSignature;
	private String applicationSignDate;
	private String intakeCounselorSignDate;
	private String directorSignDate;
	private String cellDisclosureConsent;
	private String releaseWaiverConsent;
	private String biblicalCounselingConsent;
	private String entryAgreementConsent;
	private String rulesVisitationConsent;
	private String releaseInformationConsent;
	private String creationDate;
	private String createdBy;
	private String lastUpdatedDate;
	private String lastUpdatedBy;
	private String submissionDate;
	private String entryDate;
	private String intakeStatus;
	private byte[] imageHeadshot;
	private byte[] imageStateId;
	private byte[] imageSsn;
	private String probationState;
	private String relationshipWithMother;
	private String relationshipWithFather;
	private String medicalConditionDetails;
	private String herniaDate;
	private String otherJobSkill;
	private String farmBase;
	private String exitDate;
	private String supervisor;
	private String job;
	private String class_;
	private String area;
	private String room;
	private String bed;
	private String archivedFlag;
	private Long departmentId;
	private Long supervisorId;
	private Long jobId;
	private String otherBenefits;
	private String aaYears;
	private String lawsuitDate;
	private String currentLawsuitDate;
	private Integer felonyQty;
	private String needMedicationFlag;
	private String employer1Name;
	private String employer2Name;
	private String employer3Name;
	private String employer1Dates;
	private String employer2Dates;
	private String employer3Dates;
	private String employer4Dates;
	private String employer1Contact;
	private String employer2Contact;
	private String employer3Contact;
	private String employer4Contact;
	private String employer1Phone;
	private String employer2Phone;
	private String employer3Phone;
	private String employer4Phone;
	private String employer1Job;
	private String employer2Job;
	private String employer3Job;
	private String employer4Job;
	private String employer4Name;

	public Intake() {
	}

	public Intake(String lastname, String firstname, String mi, String suffix,
			String address, String city, String state, String zipcode,
			String dob, String ssn, String ssnCardFlag, String age,
			String height, String weight, String ethnicity, String hairColor,
			String eyeColor, String maritalStatus, String educationLevel,
			String graduateFlag, String transcriptsFlag,
			String englishSpeakingFlag, String englishReadingFlag,
			String homeLocation, String referredBy, String referredByPhone,
			String emergencyContact, String emergencyPhone,
			String emergencryRelationship, String motherLivingFlag,
			String fatherLivingFlag, String brothers, String sisters,
			String children, String veteranStatus, String branchOfService,
			String rank, String lengthOfService, String dlFlag,
			String dlNumber, String dlState, String dlExpDate,
			String stateIdFlag, String stateIdState, String stateIdExpDate,
			String governmentBenefitsFlag, String religion,
			String religiousExperience, String alcoholLastUsed,
			String cocaineLastUsed, String marijuanaLastUsed,
			String oxycodoneLastUsed, String speedLastUsed,
			String heroinLastUsed, String xanaxLastUsed, String otherLastUsed,
			String alcoholYearsUsed, String cocaineYearsUsed,
			String marijuanaYearsUsed, String oxycodoneYearsUsed,
			String speedYearsUsed, String heroinYearsUsed,
			String xanaxYearsUsed, String otherYearsUsed, String sober1Year,
			String sober3Years, String usagePattern, String quantityPerWeek,
			String quantity2Years, String usageLosses, String physicalEffects,
			String aaFlag, String naFlag, String prevFfFlag, String prevFfYear,
			String prevFfOther, String currentHealth, String medicationFlag,
			String medicationSupplyFlag, String medicationNeedFlag,
			String medicationDetails, String medicationRefillDetails,
			String doctorApptFlag, String doctorApptDetails,
			String eyewearFlag, String eyewearUsage, String homelessTime,
			String homelessReason, String homelessHowOften,
			String industrialInjuryFlag, String industrialInjuryDate,
			String industrialInjuryReason, String industrialInjuryLocation,
			String industrialInjuryEmployer,
			String industrialInjuryClaimStatus, String disabilityFlag,
			String disabilityDetails, String disabilityExaminationDate,
			String disabilityPhysician, String disabilityPhysicianAddress,
			String herniaSide, String herniaOperationFlag,
			String herniaDetails, String lawsuitFlag,
			String currentLawsuitFlag, String lawsuitDetails,
			String currentLawsuitDetails, String felonyFlag,
			String sexualOffenseFlag, String felonyDetails,
			String sexualOffenseQty, String sexualOffenseDetails,
			String probationFlag, String probationCounty,
			String probationOfficer, String probationOfficerPhone,
			String probationApptFlag, String probationApptDetails,
			String incomeAmount, String incomeSource, String incomeWeeklyFlag,
			String incomeMonthlyFlag, String applicationStatus,
			String applicationSignature, String intakeCounselorSignature,
			String directorSignature, String applicationSignDate,
			String intakeCounselorSignDate, String directorSignDate,
			String cellDisclosureConsent, String releaseWaiverConsent,
			String biblicalCounselingConsent, String entryAgreementConsent,
			String rulesVisitationConsent, String releaseInformationConsent,
			String creationDate, String createdBy, String lastUpdatedDate,
			String lastUpdatedBy, String submissionDate, String entryDate,
			String intakeStatus, byte[] imageHeadshot, byte[] imageStateId,
			byte[] imageSsn, String probationState,
			String relationshipWithMother, String relationshipWithFather,
			String medicalConditionDetails, String herniaDate,
			String otherJobSkill, String farmBase, String exitDate,
			String supervisor, String job, String class_, String area,
			String room, String bed, String archivedFlag, Long departmentId,
			Long supervisorId, Long jobId, String otherBenefits,
			String aaYears, String lawsuitDate, String currentLawsuitDate,
			Integer felonyQty, String needMedicationFlag, String employer1Name,
			String employer2Name, String employer3Name, String employer1Dates,
			String employer2Dates, String employer3Dates,
			String employer4Dates, String employer1Contact,
			String employer2Contact, String employer3Contact,
			String employer4Contact, String employer1Phone,
			String employer2Phone, String employer3Phone,
			String employer4Phone, String employer1Job, String employer2Job,
			String employer3Job, String employer4Job, String employer4Name) {
		this.lastname = lastname;
		this.firstname = firstname;
		this.mi = mi;
		this.suffix = suffix;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.dob = dob;
		this.ssn = ssn;
		this.ssnCardFlag = ssnCardFlag;
		this.age = age;
		this.height = height;
		this.weight = weight;
		this.ethnicity = ethnicity;
		this.hairColor = hairColor;
		this.eyeColor = eyeColor;
		this.maritalStatus = maritalStatus;
		this.educationLevel = educationLevel;
		this.graduateFlag = graduateFlag;
		this.transcriptsFlag = transcriptsFlag;
		this.englishSpeakingFlag = englishSpeakingFlag;
		this.englishReadingFlag = englishReadingFlag;
		this.homeLocation = homeLocation;
		this.referredBy = referredBy;
		this.referredByPhone = referredByPhone;
		this.emergencyContact = emergencyContact;
		this.emergencyPhone = emergencyPhone;
		this.emergencryRelationship = emergencryRelationship;
		this.motherLivingFlag = motherLivingFlag;
		this.fatherLivingFlag = fatherLivingFlag;
		this.brothers = brothers;
		this.sisters = sisters;
		this.children = children;
		this.veteranStatus = veteranStatus;
		this.branchOfService = branchOfService;
		this.rank = rank;
		this.lengthOfService = lengthOfService;
		this.dlFlag = dlFlag;
		this.dlNumber = dlNumber;
		this.dlState = dlState;
		this.dlExpDate = dlExpDate;
		this.stateIdFlag = stateIdFlag;
		this.stateIdState = stateIdState;
		this.stateIdExpDate = stateIdExpDate;
		this.governmentBenefitsFlag = governmentBenefitsFlag;
		this.religion = religion;
		this.religiousExperience = religiousExperience;
		this.alcoholLastUsed = alcoholLastUsed;
		this.cocaineLastUsed = cocaineLastUsed;
		this.marijuanaLastUsed = marijuanaLastUsed;
		this.oxycodoneLastUsed = oxycodoneLastUsed;
		this.speedLastUsed = speedLastUsed;
		this.heroinLastUsed = heroinLastUsed;
		this.xanaxLastUsed = xanaxLastUsed;
		this.otherLastUsed = otherLastUsed;
		this.alcoholYearsUsed = alcoholYearsUsed;
		this.cocaineYearsUsed = cocaineYearsUsed;
		this.marijuanaYearsUsed = marijuanaYearsUsed;
		this.oxycodoneYearsUsed = oxycodoneYearsUsed;
		this.speedYearsUsed = speedYearsUsed;
		this.heroinYearsUsed = heroinYearsUsed;
		this.xanaxYearsUsed = xanaxYearsUsed;
		this.otherYearsUsed = otherYearsUsed;
		this.sober1Year = sober1Year;
		this.sober3Years = sober3Years;
		this.usagePattern = usagePattern;
		this.quantityPerWeek = quantityPerWeek;
		this.quantity2Years = quantity2Years;
		this.usageLosses = usageLosses;
		this.physicalEffects = physicalEffects;
		this.aaFlag = aaFlag;
		this.naFlag = naFlag;
		this.prevFfFlag = prevFfFlag;
		this.prevFfYear = prevFfYear;
		this.prevFfOther = prevFfOther;
		this.currentHealth = currentHealth;
		this.medicationFlag = medicationFlag;
		this.medicationSupplyFlag = medicationSupplyFlag;
		this.medicationNeedFlag = medicationNeedFlag;
		this.medicationDetails = medicationDetails;
		this.medicationRefillDetails = medicationRefillDetails;
		this.doctorApptFlag = doctorApptFlag;
		this.doctorApptDetails = doctorApptDetails;
		this.eyewearFlag = eyewearFlag;
		this.eyewearUsage = eyewearUsage;
		this.homelessTime = homelessTime;
		this.homelessReason = homelessReason;
		this.homelessHowOften = homelessHowOften;
		this.industrialInjuryFlag = industrialInjuryFlag;
		this.industrialInjuryDate = industrialInjuryDate;
		this.industrialInjuryReason = industrialInjuryReason;
		this.industrialInjuryLocation = industrialInjuryLocation;
		this.industrialInjuryEmployer = industrialInjuryEmployer;
		this.industrialInjuryClaimStatus = industrialInjuryClaimStatus;
		this.disabilityFlag = disabilityFlag;
		this.disabilityDetails = disabilityDetails;
		this.disabilityExaminationDate = disabilityExaminationDate;
		this.disabilityPhysician = disabilityPhysician;
		this.disabilityPhysicianAddress = disabilityPhysicianAddress;
		this.herniaSide = herniaSide;
		this.herniaOperationFlag = herniaOperationFlag;
		this.herniaDetails = herniaDetails;
		this.lawsuitFlag = lawsuitFlag;
		this.currentLawsuitFlag = currentLawsuitFlag;
		this.lawsuitDetails = lawsuitDetails;
		this.currentLawsuitDetails = currentLawsuitDetails;
		this.felonyFlag = felonyFlag;
		this.sexualOffenseFlag = sexualOffenseFlag;
		this.felonyDetails = felonyDetails;
		this.sexualOffenseQty = sexualOffenseQty;
		this.sexualOffenseDetails = sexualOffenseDetails;
		this.probationFlag = probationFlag;
		this.probationCounty = probationCounty;
		this.probationOfficer = probationOfficer;
		this.probationOfficerPhone = probationOfficerPhone;
		this.probationApptFlag = probationApptFlag;
		this.probationApptDetails = probationApptDetails;
		this.incomeAmount = incomeAmount;
		this.incomeSource = incomeSource;
		this.incomeWeeklyFlag = incomeWeeklyFlag;
		this.incomeMonthlyFlag = incomeMonthlyFlag;
		this.applicationStatus = applicationStatus;
		this.applicationSignature = applicationSignature;
		this.intakeCounselorSignature = intakeCounselorSignature;
		this.directorSignature = directorSignature;
		this.applicationSignDate = applicationSignDate;
		this.intakeCounselorSignDate = intakeCounselorSignDate;
		this.directorSignDate = directorSignDate;
		this.cellDisclosureConsent = cellDisclosureConsent;
		this.releaseWaiverConsent = releaseWaiverConsent;
		this.biblicalCounselingConsent = biblicalCounselingConsent;
		this.entryAgreementConsent = entryAgreementConsent;
		this.rulesVisitationConsent = rulesVisitationConsent;
		this.releaseInformationConsent = releaseInformationConsent;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.submissionDate = submissionDate;
		this.entryDate = entryDate;
		this.intakeStatus = intakeStatus;
		this.imageHeadshot = imageHeadshot;
		this.imageStateId = imageStateId;
		this.imageSsn = imageSsn;
		this.probationState = probationState;
		this.relationshipWithMother = relationshipWithMother;
		this.relationshipWithFather = relationshipWithFather;
		this.medicalConditionDetails = medicalConditionDetails;
		this.herniaDate = herniaDate;
		this.otherJobSkill = otherJobSkill;
		this.farmBase = farmBase;
		this.exitDate = exitDate;
		this.supervisor = supervisor;
		this.job = job;
		this.class_ = class_;
		this.area = area;
		this.room = room;
		this.bed = bed;
		this.archivedFlag = archivedFlag;
		this.departmentId = departmentId;
		this.supervisorId = supervisorId;
		this.jobId = jobId;
		this.otherBenefits = otherBenefits;
		this.aaYears = aaYears;
		this.lawsuitDate = lawsuitDate;
		this.currentLawsuitDate = currentLawsuitDate;
		this.felonyQty = felonyQty;
		this.needMedicationFlag = needMedicationFlag;
		this.employer1Name = employer1Name;
		this.employer2Name = employer2Name;
		this.employer3Name = employer3Name;
		this.employer1Dates = employer1Dates;
		this.employer2Dates = employer2Dates;
		this.employer3Dates = employer3Dates;
		this.employer4Dates = employer4Dates;
		this.employer1Contact = employer1Contact;
		this.employer2Contact = employer2Contact;
		this.employer3Contact = employer3Contact;
		this.employer4Contact = employer4Contact;
		this.employer1Phone = employer1Phone;
		this.employer2Phone = employer2Phone;
		this.employer3Phone = employer3Phone;
		this.employer4Phone = employer4Phone;
		this.employer1Job = employer1Job;
		this.employer2Job = employer2Job;
		this.employer3Job = employer3Job;
		this.employer4Job = employer4Job;
		this.employer4Name = employer4Name;
	}

	public Integer getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(Integer intakeId) {
		this.intakeId = intakeId;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getMi() {
		return this.mi;
	}

	public void setMi(String mi) {
		this.mi = mi;
	}

	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	public String getSsnCardFlag() {
		return this.ssnCardFlag;
	}

	public void setSsnCardFlag(String ssnCardFlag) {
		this.ssnCardFlag = ssnCardFlag;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getEthnicity() {
		return this.ethnicity;
	}

	public void setEthnicity(String ethnicity) {
		this.ethnicity = ethnicity;
	}

	public String getHairColor() {
		return this.hairColor;
	}

	public void setHairColor(String hairColor) {
		this.hairColor = hairColor;
	}

	public String getEyeColor() {
		return this.eyeColor;
	}

	public void setEyeColor(String eyeColor) {
		this.eyeColor = eyeColor;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getEducationLevel() {
		return this.educationLevel;
	}

	public void setEducationLevel(String educationLevel) {
		this.educationLevel = educationLevel;
	}

	public String getGraduateFlag() {
		return this.graduateFlag;
	}

	public void setGraduateFlag(String graduateFlag) {
		this.graduateFlag = graduateFlag;
	}

	public String getTranscriptsFlag() {
		return this.transcriptsFlag;
	}

	public void setTranscriptsFlag(String transcriptsFlag) {
		this.transcriptsFlag = transcriptsFlag;
	}

	public String getEnglishSpeakingFlag() {
		return this.englishSpeakingFlag;
	}

	public void setEnglishSpeakingFlag(String englishSpeakingFlag) {
		this.englishSpeakingFlag = englishSpeakingFlag;
	}

	public String getEnglishReadingFlag() {
		return this.englishReadingFlag;
	}

	public void setEnglishReadingFlag(String englishReadingFlag) {
		this.englishReadingFlag = englishReadingFlag;
	}

	public String getHomeLocation() {
		return this.homeLocation;
	}

	public void setHomeLocation(String homeLocation) {
		this.homeLocation = homeLocation;
	}

	public String getReferredBy() {
		return this.referredBy;
	}

	public void setReferredBy(String referredBy) {
		this.referredBy = referredBy;
	}

	public String getReferredByPhone() {
		return this.referredByPhone;
	}

	public void setReferredByPhone(String referredByPhone) {
		this.referredByPhone = referredByPhone;
	}

	public String getEmergencyContact() {
		return this.emergencyContact;
	}

	public void setEmergencyContact(String emergencyContact) {
		this.emergencyContact = emergencyContact;
	}

	public String getEmergencyPhone() {
		return this.emergencyPhone;
	}

	public void setEmergencyPhone(String emergencyPhone) {
		this.emergencyPhone = emergencyPhone;
	}

	public String getEmergencryRelationship() {
		return this.emergencryRelationship;
	}

	public void setEmergencryRelationship(String emergencryRelationship) {
		this.emergencryRelationship = emergencryRelationship;
	}

	public String getMotherLivingFlag() {
		return this.motherLivingFlag;
	}

	public void setMotherLivingFlag(String motherLivingFlag) {
		this.motherLivingFlag = motherLivingFlag;
	}

	public String getFatherLivingFlag() {
		return this.fatherLivingFlag;
	}

	public void setFatherLivingFlag(String fatherLivingFlag) {
		this.fatherLivingFlag = fatherLivingFlag;
	}

	public String getBrothers() {
		return this.brothers;
	}

	public void setBrothers(String brothers) {
		this.brothers = brothers;
	}

	public String getSisters() {
		return this.sisters;
	}

	public void setSisters(String sisters) {
		this.sisters = sisters;
	}

	public String getChildren() {
		return this.children;
	}

	public void setChildren(String children) {
		this.children = children;
	}

	public String getVeteranStatus() {
		return this.veteranStatus;
	}

	public void setVeteranStatus(String veteranStatus) {
		this.veteranStatus = veteranStatus;
	}

	public String getBranchOfService() {
		return this.branchOfService;
	}

	public void setBranchOfService(String branchOfService) {
		this.branchOfService = branchOfService;
	}

	public String getRank() {
		return this.rank;
	}

	public void setRank(String rank) {
		this.rank = rank;
	}

	public String getLengthOfService() {
		return this.lengthOfService;
	}

	public void setLengthOfService(String lengthOfService) {
		this.lengthOfService = lengthOfService;
	}

	public String getDlFlag() {
		return this.dlFlag;
	}

	public void setDlFlag(String dlFlag) {
		this.dlFlag = dlFlag;
	}

	public String getDlNumber() {
		return this.dlNumber;
	}

	public void setDlNumber(String dlNumber) {
		this.dlNumber = dlNumber;
	}

	public String getDlState() {
		return this.dlState;
	}

	public void setDlState(String dlState) {
		this.dlState = dlState;
	}

	public String getDlExpDate() {
		return this.dlExpDate;
	}

	public void setDlExpDate(String dlExpDate) {
		this.dlExpDate = dlExpDate;
	}

	public String getStateIdFlag() {
		return this.stateIdFlag;
	}

	public void setStateIdFlag(String stateIdFlag) {
		this.stateIdFlag = stateIdFlag;
	}

	public String getStateIdState() {
		return this.stateIdState;
	}

	public void setStateIdState(String stateIdState) {
		this.stateIdState = stateIdState;
	}

	public String getStateIdExpDate() {
		return this.stateIdExpDate;
	}

	public void setStateIdExpDate(String stateIdExpDate) {
		this.stateIdExpDate = stateIdExpDate;
	}

	public String getGovernmentBenefitsFlag() {
		return this.governmentBenefitsFlag;
	}

	public void setGovernmentBenefitsFlag(String governmentBenefitsFlag) {
		this.governmentBenefitsFlag = governmentBenefitsFlag;
	}

	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	public String getReligiousExperience() {
		return this.religiousExperience;
	}

	public void setReligiousExperience(String religiousExperience) {
		this.religiousExperience = religiousExperience;
	}

	public String getAlcoholLastUsed() {
		return this.alcoholLastUsed;
	}

	public void setAlcoholLastUsed(String alcoholLastUsed) {
		this.alcoholLastUsed = alcoholLastUsed;
	}

	public String getCocaineLastUsed() {
		return this.cocaineLastUsed;
	}

	public void setCocaineLastUsed(String cocaineLastUsed) {
		this.cocaineLastUsed = cocaineLastUsed;
	}

	public String getMarijuanaLastUsed() {
		return this.marijuanaLastUsed;
	}

	public void setMarijuanaLastUsed(String marijuanaLastUsed) {
		this.marijuanaLastUsed = marijuanaLastUsed;
	}

	public String getOxycodoneLastUsed() {
		return this.oxycodoneLastUsed;
	}

	public void setOxycodoneLastUsed(String oxycodoneLastUsed) {
		this.oxycodoneLastUsed = oxycodoneLastUsed;
	}

	public String getSpeedLastUsed() {
		return this.speedLastUsed;
	}

	public void setSpeedLastUsed(String speedLastUsed) {
		this.speedLastUsed = speedLastUsed;
	}

	public String getHeroinLastUsed() {
		return this.heroinLastUsed;
	}

	public void setHeroinLastUsed(String heroinLastUsed) {
		this.heroinLastUsed = heroinLastUsed;
	}

	public String getXanaxLastUsed() {
		return this.xanaxLastUsed;
	}

	public void setXanaxLastUsed(String xanaxLastUsed) {
		this.xanaxLastUsed = xanaxLastUsed;
	}

	public String getOtherLastUsed() {
		return this.otherLastUsed;
	}

	public void setOtherLastUsed(String otherLastUsed) {
		this.otherLastUsed = otherLastUsed;
	}

	public String getAlcoholYearsUsed() {
		return this.alcoholYearsUsed;
	}

	public void setAlcoholYearsUsed(String alcoholYearsUsed) {
		this.alcoholYearsUsed = alcoholYearsUsed;
	}

	public String getCocaineYearsUsed() {
		return this.cocaineYearsUsed;
	}

	public void setCocaineYearsUsed(String cocaineYearsUsed) {
		this.cocaineYearsUsed = cocaineYearsUsed;
	}

	public String getMarijuanaYearsUsed() {
		return this.marijuanaYearsUsed;
	}

	public void setMarijuanaYearsUsed(String marijuanaYearsUsed) {
		this.marijuanaYearsUsed = marijuanaYearsUsed;
	}

	public String getOxycodoneYearsUsed() {
		return this.oxycodoneYearsUsed;
	}

	public void setOxycodoneYearsUsed(String oxycodoneYearsUsed) {
		this.oxycodoneYearsUsed = oxycodoneYearsUsed;
	}

	public String getSpeedYearsUsed() {
		return this.speedYearsUsed;
	}

	public void setSpeedYearsUsed(String speedYearsUsed) {
		this.speedYearsUsed = speedYearsUsed;
	}

	public String getHeroinYearsUsed() {
		return this.heroinYearsUsed;
	}

	public void setHeroinYearsUsed(String heroinYearsUsed) {
		this.heroinYearsUsed = heroinYearsUsed;
	}

	public String getXanaxYearsUsed() {
		return this.xanaxYearsUsed;
	}

	public void setXanaxYearsUsed(String xanaxYearsUsed) {
		this.xanaxYearsUsed = xanaxYearsUsed;
	}

	public String getOtherYearsUsed() {
		return this.otherYearsUsed;
	}

	public void setOtherYearsUsed(String otherYearsUsed) {
		this.otherYearsUsed = otherYearsUsed;
	}

	public String getSober1Year() {
		return this.sober1Year;
	}

	public void setSober1Year(String sober1Year) {
		this.sober1Year = sober1Year;
	}

	public String getSober3Years() {
		return this.sober3Years;
	}

	public void setSober3Years(String sober3Years) {
		this.sober3Years = sober3Years;
	}

	public String getUsagePattern() {
		return this.usagePattern;
	}

	public void setUsagePattern(String usagePattern) {
		this.usagePattern = usagePattern;
	}

	public String getQuantityPerWeek() {
		return this.quantityPerWeek;
	}

	public void setQuantityPerWeek(String quantityPerWeek) {
		this.quantityPerWeek = quantityPerWeek;
	}

	public String getQuantity2Years() {
		return this.quantity2Years;
	}

	public void setQuantity2Years(String quantity2Years) {
		this.quantity2Years = quantity2Years;
	}

	public String getUsageLosses() {
		return this.usageLosses;
	}

	public void setUsageLosses(String usageLosses) {
		this.usageLosses = usageLosses;
	}

	public String getPhysicalEffects() {
		return this.physicalEffects;
	}

	public void setPhysicalEffects(String physicalEffects) {
		this.physicalEffects = physicalEffects;
	}

	public String getAaFlag() {
		return this.aaFlag;
	}

	public void setAaFlag(String aaFlag) {
		this.aaFlag = aaFlag;
	}

	public String getNaFlag() {
		return this.naFlag;
	}

	public void setNaFlag(String naFlag) {
		this.naFlag = naFlag;
	}

	public String getPrevFfFlag() {
		return this.prevFfFlag;
	}

	public void setPrevFfFlag(String prevFfFlag) {
		this.prevFfFlag = prevFfFlag;
	}

	public String getPrevFfYear() {
		return this.prevFfYear;
	}

	public void setPrevFfYear(String prevFfYear) {
		this.prevFfYear = prevFfYear;
	}

	public String getPrevFfOther() {
		return this.prevFfOther;
	}

	public void setPrevFfOther(String prevFfOther) {
		this.prevFfOther = prevFfOther;
	}

	public String getCurrentHealth() {
		return this.currentHealth;
	}

	public void setCurrentHealth(String currentHealth) {
		this.currentHealth = currentHealth;
	}

	public String getMedicationFlag() {
		return this.medicationFlag;
	}

	public void setMedicationFlag(String medicationFlag) {
		this.medicationFlag = medicationFlag;
	}

	public String getMedicationSupplyFlag() {
		return this.medicationSupplyFlag;
	}

	public void setMedicationSupplyFlag(String medicationSupplyFlag) {
		this.medicationSupplyFlag = medicationSupplyFlag;
	}

	public String getMedicationNeedFlag() {
		return this.medicationNeedFlag;
	}

	public void setMedicationNeedFlag(String medicationNeedFlag) {
		this.medicationNeedFlag = medicationNeedFlag;
	}

	public String getMedicationDetails() {
		return this.medicationDetails;
	}

	public void setMedicationDetails(String medicationDetails) {
		this.medicationDetails = medicationDetails;
	}

	public String getMedicationRefillDetails() {
		return this.medicationRefillDetails;
	}

	public void setMedicationRefillDetails(String medicationRefillDetails) {
		this.medicationRefillDetails = medicationRefillDetails;
	}

	public String getDoctorApptFlag() {
		return this.doctorApptFlag;
	}

	public void setDoctorApptFlag(String doctorApptFlag) {
		this.doctorApptFlag = doctorApptFlag;
	}

	public String getDoctorApptDetails() {
		return this.doctorApptDetails;
	}

	public void setDoctorApptDetails(String doctorApptDetails) {
		this.doctorApptDetails = doctorApptDetails;
	}

	public String getEyewearFlag() {
		return this.eyewearFlag;
	}

	public void setEyewearFlag(String eyewearFlag) {
		this.eyewearFlag = eyewearFlag;
	}

	public String getEyewearUsage() {
		return this.eyewearUsage;
	}

	public void setEyewearUsage(String eyewearUsage) {
		this.eyewearUsage = eyewearUsage;
	}

	public String getHomelessTime() {
		return this.homelessTime;
	}

	public void setHomelessTime(String homelessTime) {
		this.homelessTime = homelessTime;
	}

	public String getHomelessReason() {
		return this.homelessReason;
	}

	public void setHomelessReason(String homelessReason) {
		this.homelessReason = homelessReason;
	}

	public String getHomelessHowOften() {
		return this.homelessHowOften;
	}

	public void setHomelessHowOften(String homelessHowOften) {
		this.homelessHowOften = homelessHowOften;
	}

	public String getIndustrialInjuryFlag() {
		return this.industrialInjuryFlag;
	}

	public void setIndustrialInjuryFlag(String industrialInjuryFlag) {
		this.industrialInjuryFlag = industrialInjuryFlag;
	}

	public String getIndustrialInjuryDate() {
		return this.industrialInjuryDate;
	}

	public void setIndustrialInjuryDate(String industrialInjuryDate) {
		this.industrialInjuryDate = industrialInjuryDate;
	}

	public String getIndustrialInjuryReason() {
		return this.industrialInjuryReason;
	}

	public void setIndustrialInjuryReason(String industrialInjuryReason) {
		this.industrialInjuryReason = industrialInjuryReason;
	}

	public String getIndustrialInjuryLocation() {
		return this.industrialInjuryLocation;
	}

	public void setIndustrialInjuryLocation(String industrialInjuryLocation) {
		this.industrialInjuryLocation = industrialInjuryLocation;
	}

	public String getIndustrialInjuryEmployer() {
		return this.industrialInjuryEmployer;
	}

	public void setIndustrialInjuryEmployer(String industrialInjuryEmployer) {
		this.industrialInjuryEmployer = industrialInjuryEmployer;
	}

	public String getIndustrialInjuryClaimStatus() {
		return this.industrialInjuryClaimStatus;
	}

	public void setIndustrialInjuryClaimStatus(
			String industrialInjuryClaimStatus) {
		this.industrialInjuryClaimStatus = industrialInjuryClaimStatus;
	}

	public String getDisabilityFlag() {
		return this.disabilityFlag;
	}

	public void setDisabilityFlag(String disabilityFlag) {
		this.disabilityFlag = disabilityFlag;
	}

	public String getDisabilityDetails() {
		return this.disabilityDetails;
	}

	public void setDisabilityDetails(String disabilityDetails) {
		this.disabilityDetails = disabilityDetails;
	}

	public String getDisabilityExaminationDate() {
		return this.disabilityExaminationDate;
	}

	public void setDisabilityExaminationDate(String disabilityExaminationDate) {
		this.disabilityExaminationDate = disabilityExaminationDate;
	}

	public String getDisabilityPhysician() {
		return this.disabilityPhysician;
	}

	public void setDisabilityPhysician(String disabilityPhysician) {
		this.disabilityPhysician = disabilityPhysician;
	}

	public String getDisabilityPhysicianAddress() {
		return this.disabilityPhysicianAddress;
	}

	public void setDisabilityPhysicianAddress(String disabilityPhysicianAddress) {
		this.disabilityPhysicianAddress = disabilityPhysicianAddress;
	}

	public String getHerniaSide() {
		return this.herniaSide;
	}

	public void setHerniaSide(String herniaSide) {
		this.herniaSide = herniaSide;
	}

	public String getHerniaOperationFlag() {
		return this.herniaOperationFlag;
	}

	public void setHerniaOperationFlag(String herniaOperationFlag) {
		this.herniaOperationFlag = herniaOperationFlag;
	}

	public String getHerniaDetails() {
		return this.herniaDetails;
	}

	public void setHerniaDetails(String herniaDetails) {
		this.herniaDetails = herniaDetails;
	}

	public String getLawsuitFlag() {
		return this.lawsuitFlag;
	}

	public void setLawsuitFlag(String lawsuitFlag) {
		this.lawsuitFlag = lawsuitFlag;
	}

	public String getCurrentLawsuitFlag() {
		return this.currentLawsuitFlag;
	}

	public void setCurrentLawsuitFlag(String currentLawsuitFlag) {
		this.currentLawsuitFlag = currentLawsuitFlag;
	}

	public String getLawsuitDetails() {
		return this.lawsuitDetails;
	}

	public void setLawsuitDetails(String lawsuitDetails) {
		this.lawsuitDetails = lawsuitDetails;
	}

	public String getCurrentLawsuitDetails() {
		return this.currentLawsuitDetails;
	}

	public void setCurrentLawsuitDetails(String currentLawsuitDetails) {
		this.currentLawsuitDetails = currentLawsuitDetails;
	}

	public String getFelonyFlag() {
		return this.felonyFlag;
	}

	public void setFelonyFlag(String felonyFlag) {
		this.felonyFlag = felonyFlag;
	}

	public String getSexualOffenseFlag() {
		return this.sexualOffenseFlag;
	}

	public void setSexualOffenseFlag(String sexualOffenseFlag) {
		this.sexualOffenseFlag = sexualOffenseFlag;
	}

	public String getFelonyDetails() {
		return this.felonyDetails;
	}

	public void setFelonyDetails(String felonyDetails) {
		this.felonyDetails = felonyDetails;
	}

	public String getSexualOffenseQty() {
		return this.sexualOffenseQty;
	}

	public void setSexualOffenseQty(String sexualOffenseQty) {
		this.sexualOffenseQty = sexualOffenseQty;
	}

	public String getSexualOffenseDetails() {
		return this.sexualOffenseDetails;
	}

	public void setSexualOffenseDetails(String sexualOffenseDetails) {
		this.sexualOffenseDetails = sexualOffenseDetails;
	}

	public String getProbationFlag() {
		return this.probationFlag;
	}

	public void setProbationFlag(String probationFlag) {
		this.probationFlag = probationFlag;
	}

	public String getProbationCounty() {
		return this.probationCounty;
	}

	public void setProbationCounty(String probationCounty) {
		this.probationCounty = probationCounty;
	}

	public String getProbationOfficer() {
		return this.probationOfficer;
	}

	public void setProbationOfficer(String probationOfficer) {
		this.probationOfficer = probationOfficer;
	}

	public String getProbationOfficerPhone() {
		return this.probationOfficerPhone;
	}

	public void setProbationOfficerPhone(String probationOfficerPhone) {
		this.probationOfficerPhone = probationOfficerPhone;
	}

	public String getProbationApptFlag() {
		return this.probationApptFlag;
	}

	public void setProbationApptFlag(String probationApptFlag) {
		this.probationApptFlag = probationApptFlag;
	}

	public String getProbationApptDetails() {
		return this.probationApptDetails;
	}

	public void setProbationApptDetails(String probationApptDetails) {
		this.probationApptDetails = probationApptDetails;
	}

	public String getIncomeAmount() {
		return this.incomeAmount;
	}

	public void setIncomeAmount(String incomeAmount) {
		this.incomeAmount = incomeAmount;
	}

	public String getIncomeSource() {
		return this.incomeSource;
	}

	public void setIncomeSource(String incomeSource) {
		this.incomeSource = incomeSource;
	}

	public String getIncomeWeeklyFlag() {
		return this.incomeWeeklyFlag;
	}

	public void setIncomeWeeklyFlag(String incomeWeeklyFlag) {
		this.incomeWeeklyFlag = incomeWeeklyFlag;
	}

	public String getIncomeMonthlyFlag() {
		return this.incomeMonthlyFlag;
	}

	public void setIncomeMonthlyFlag(String incomeMonthlyFlag) {
		this.incomeMonthlyFlag = incomeMonthlyFlag;
	}

	public String getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public String getApplicationSignature() {
		return this.applicationSignature;
	}

	public void setApplicationSignature(String applicationSignature) {
		this.applicationSignature = applicationSignature;
	}

	public String getIntakeCounselorSignature() {
		return this.intakeCounselorSignature;
	}

	public void setIntakeCounselorSignature(String intakeCounselorSignature) {
		this.intakeCounselorSignature = intakeCounselorSignature;
	}

	public String getDirectorSignature() {
		return this.directorSignature;
	}

	public void setDirectorSignature(String directorSignature) {
		this.directorSignature = directorSignature;
	}

	public String getApplicationSignDate() {
		return this.applicationSignDate;
	}

	public void setApplicationSignDate(String applicationSignDate) {
		this.applicationSignDate = applicationSignDate;
	}

	public String getIntakeCounselorSignDate() {
		return this.intakeCounselorSignDate;
	}

	public void setIntakeCounselorSignDate(String intakeCounselorSignDate) {
		this.intakeCounselorSignDate = intakeCounselorSignDate;
	}

	public String getDirectorSignDate() {
		return this.directorSignDate;
	}

	public void setDirectorSignDate(String directorSignDate) {
		this.directorSignDate = directorSignDate;
	}

	public String getCellDisclosureConsent() {
		return this.cellDisclosureConsent;
	}

	public void setCellDisclosureConsent(String cellDisclosureConsent) {
		this.cellDisclosureConsent = cellDisclosureConsent;
	}

	public String getReleaseWaiverConsent() {
		return this.releaseWaiverConsent;
	}

	public void setReleaseWaiverConsent(String releaseWaiverConsent) {
		this.releaseWaiverConsent = releaseWaiverConsent;
	}

	public String getBiblicalCounselingConsent() {
		return this.biblicalCounselingConsent;
	}

	public void setBiblicalCounselingConsent(String biblicalCounselingConsent) {
		this.biblicalCounselingConsent = biblicalCounselingConsent;
	}

	public String getEntryAgreementConsent() {
		return this.entryAgreementConsent;
	}

	public void setEntryAgreementConsent(String entryAgreementConsent) {
		this.entryAgreementConsent = entryAgreementConsent;
	}

	public String getRulesVisitationConsent() {
		return this.rulesVisitationConsent;
	}

	public void setRulesVisitationConsent(String rulesVisitationConsent) {
		this.rulesVisitationConsent = rulesVisitationConsent;
	}

	public String getReleaseInformationConsent() {
		return this.releaseInformationConsent;
	}

	public void setReleaseInformationConsent(String releaseInformationConsent) {
		this.releaseInformationConsent = releaseInformationConsent;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getSubmissionDate() {
		return this.submissionDate;
	}

	public void setSubmissionDate(String submissionDate) {
		this.submissionDate = submissionDate;
	}

	public String getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(String entryDate) {
		this.entryDate = entryDate;
	}

	public String getIntakeStatus() {
		return this.intakeStatus;
	}

	public void setIntakeStatus(String intakeStatus) {
		this.intakeStatus = intakeStatus;
	}

	public byte[] getImageHeadshot() {
		return this.imageHeadshot;
	}

	public void setImageHeadshot(byte[] imageHeadshot) {
		this.imageHeadshot = imageHeadshot;
	}

	public byte[] getImageStateId() {
		return this.imageStateId;
	}

	public void setImageStateId(byte[] imageStateId) {
		this.imageStateId = imageStateId;
	}

	public byte[] getImageSsn() {
		return this.imageSsn;
	}

	public void setImageSsn(byte[] imageSsn) {
		this.imageSsn = imageSsn;
	}

	public String getProbationState() {
		return this.probationState;
	}

	public void setProbationState(String probationState) {
		this.probationState = probationState;
	}

	public String getRelationshipWithMother() {
		return this.relationshipWithMother;
	}

	public void setRelationshipWithMother(String relationshipWithMother) {
		this.relationshipWithMother = relationshipWithMother;
	}

	public String getRelationshipWithFather() {
		return this.relationshipWithFather;
	}

	public void setRelationshipWithFather(String relationshipWithFather) {
		this.relationshipWithFather = relationshipWithFather;
	}

	public String getMedicalConditionDetails() {
		return this.medicalConditionDetails;
	}

	public void setMedicalConditionDetails(String medicalConditionDetails) {
		this.medicalConditionDetails = medicalConditionDetails;
	}

	public String getHerniaDate() {
		return this.herniaDate;
	}

	public void setHerniaDate(String herniaDate) {
		this.herniaDate = herniaDate;
	}

	public String getOtherJobSkill() {
		return this.otherJobSkill;
	}

	public void setOtherJobSkill(String otherJobSkill) {
		this.otherJobSkill = otherJobSkill;
	}

	public String getFarmBase() {
		return this.farmBase;
	}

	public void setFarmBase(String farmBase) {
		this.farmBase = farmBase;
	}

	public String getExitDate() {
		return this.exitDate;
	}

	public void setExitDate(String exitDate) {
		this.exitDate = exitDate;
	}

	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getBed() {
		return this.bed;
	}

	public void setBed(String bed) {
		this.bed = bed;
	}

	public String getArchivedFlag() {
		return this.archivedFlag;
	}

	public void setArchivedFlag(String archivedFlag) {
		this.archivedFlag = archivedFlag;
	}

	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	public Long getSupervisorId() {
		return this.supervisorId;
	}

	public void setSupervisorId(Long supervisorId) {
		this.supervisorId = supervisorId;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public String getOtherBenefits() {
		return this.otherBenefits;
	}

	public void setOtherBenefits(String otherBenefits) {
		this.otherBenefits = otherBenefits;
	}

	public String getAaYears() {
		return this.aaYears;
	}

	public void setAaYears(String aaYears) {
		this.aaYears = aaYears;
	}

	public String getLawsuitDate() {
		return this.lawsuitDate;
	}

	public void setLawsuitDate(String lawsuitDate) {
		this.lawsuitDate = lawsuitDate;
	}

	public String getCurrentLawsuitDate() {
		return this.currentLawsuitDate;
	}

	public void setCurrentLawsuitDate(String currentLawsuitDate) {
		this.currentLawsuitDate = currentLawsuitDate;
	}

	public Integer getFelonyQty() {
		return this.felonyQty;
	}

	public void setFelonyQty(Integer felonyQty) {
		this.felonyQty = felonyQty;
	}

	public String getNeedMedicationFlag() {
		return this.needMedicationFlag;
	}

	public void setNeedMedicationFlag(String needMedicationFlag) {
		this.needMedicationFlag = needMedicationFlag;
	}

	public String getEmployer1Name() {
		return this.employer1Name;
	}

	public void setEmployer1Name(String employer1Name) {
		this.employer1Name = employer1Name;
	}

	public String getEmployer2Name() {
		return this.employer2Name;
	}

	public void setEmployer2Name(String employer2Name) {
		this.employer2Name = employer2Name;
	}

	public String getEmployer3Name() {
		return this.employer3Name;
	}

	public void setEmployer3Name(String employer3Name) {
		this.employer3Name = employer3Name;
	}

	public String getEmployer1Dates() {
		return this.employer1Dates;
	}

	public void setEmployer1Dates(String employer1Dates) {
		this.employer1Dates = employer1Dates;
	}

	public String getEmployer2Dates() {
		return this.employer2Dates;
	}

	public void setEmployer2Dates(String employer2Dates) {
		this.employer2Dates = employer2Dates;
	}

	public String getEmployer3Dates() {
		return this.employer3Dates;
	}

	public void setEmployer3Dates(String employer3Dates) {
		this.employer3Dates = employer3Dates;
	}

	public String getEmployer4Dates() {
		return this.employer4Dates;
	}

	public void setEmployer4Dates(String employer4Dates) {
		this.employer4Dates = employer4Dates;
	}

	public String getEmployer1Contact() {
		return this.employer1Contact;
	}

	public void setEmployer1Contact(String employer1Contact) {
		this.employer1Contact = employer1Contact;
	}

	public String getEmployer2Contact() {
		return this.employer2Contact;
	}

	public void setEmployer2Contact(String employer2Contact) {
		this.employer2Contact = employer2Contact;
	}

	public String getEmployer3Contact() {
		return this.employer3Contact;
	}

	public void setEmployer3Contact(String employer3Contact) {
		this.employer3Contact = employer3Contact;
	}

	public String getEmployer4Contact() {
		return this.employer4Contact;
	}

	public void setEmployer4Contact(String employer4Contact) {
		this.employer4Contact = employer4Contact;
	}

	public String getEmployer1Phone() {
		return this.employer1Phone;
	}

	public void setEmployer1Phone(String employer1Phone) {
		this.employer1Phone = employer1Phone;
	}

	public String getEmployer2Phone() {
		return this.employer2Phone;
	}

	public void setEmployer2Phone(String employer2Phone) {
		this.employer2Phone = employer2Phone;
	}

	public String getEmployer3Phone() {
		return this.employer3Phone;
	}

	public void setEmployer3Phone(String employer3Phone) {
		this.employer3Phone = employer3Phone;
	}

	public String getEmployer4Phone() {
		return this.employer4Phone;
	}

	public void setEmployer4Phone(String employer4Phone) {
		this.employer4Phone = employer4Phone;
	}

	public String getEmployer1Job() {
		return this.employer1Job;
	}

	public void setEmployer1Job(String employer1Job) {
		this.employer1Job = employer1Job;
	}

	public String getEmployer2Job() {
		return this.employer2Job;
	}

	public void setEmployer2Job(String employer2Job) {
		this.employer2Job = employer2Job;
	}

	public String getEmployer3Job() {
		return this.employer3Job;
	}

	public void setEmployer3Job(String employer3Job) {
		this.employer3Job = employer3Job;
	}

	public String getEmployer4Job() {
		return this.employer4Job;
	}

	public void setEmployer4Job(String employer4Job) {
		this.employer4Job = employer4Job;
	}

	public String getEmployer4Name() {
		return this.employer4Name;
	}

	public void setEmployer4Name(String employer4Name) {
		this.employer4Name = employer4Name;
	}

}
