package com.yada180.sms.domain;

// Generated Sep 16, 2013 10:14:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * JobSupervisor generated by hbm2java
 */
public class JobSupervisor implements java.io.Serializable {

	private long jobSupervisorId;
	private String lastname;
	private String firstname;
	private String jobAssignmentId;
	private String creationDate;
	private String createdBy;

	public JobSupervisor() {
	}

	public JobSupervisor(long jobSupervisorId) {
		this.jobSupervisorId = jobSupervisorId;
	}

	public JobSupervisor(long jobSupervisorId, String lastname,
			String firstname, String jobAssignmentId, String creationDate,
			String createdBy) {
		this.jobSupervisorId = jobSupervisorId;
		this.lastname = lastname;
		this.firstname = firstname;
		this.jobAssignmentId = jobAssignmentId;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
	}

	public long getJobSupervisorId() {
		return this.jobSupervisorId;
	}

	public void setJobSupervisorId(long jobSupervisorId) {
		this.jobSupervisorId = jobSupervisorId;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getJobAssignmentId() {
		return this.jobAssignmentId;
	}

	public void setJobAssignmentId(String jobAssignmentId) {
		this.jobAssignmentId = jobAssignmentId;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
