package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * MedicalCondition generated by hbm2java
 */
public class MedicalCondition implements java.io.Serializable {

	private Long medicalConditionId;
	private String description;
	private Integer sequence;

	public MedicalCondition() {
	}

	public MedicalCondition(String description) {
		this.description = description;
	}

	public MedicalCondition(String description, Integer sequence) {
		this.description = description;
		this.sequence = sequence;
	}

	public Long getMedicalConditionId() {
		return this.medicalConditionId;
	}

	public void setMedicalConditionId(Long medicalConditionId) {
		this.medicalConditionId = medicalConditionId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

}
