package com.yada180.sms.domain;

// Generated Sep 18, 2013 1:34:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * MedicalCondition generated by hbm2java
 */
public class MedicalCondition implements java.io.Serializable {

	private long medicalConditionId;
	private String description;
	private Integer sequence;

	public MedicalCondition() {
	}

	public MedicalCondition(long MedicalConditionId, String description) {
		this.medicalConditionId = MedicalConditionId;
		this.description = description;
	}

	public MedicalCondition(long MedicalConditionId, String description, Integer sequence) {
		this.medicalConditionId = MedicalConditionId;
		this.description = description;
		this.sequence = sequence;
	}

	public long getMedicalConditionId() {
		return this.medicalConditionId;
	}

	public void setMedicalConditionId(long MedicalConditionId) {
		this.medicalConditionId = MedicalConditionId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

}
