package com.yada180.sms.domain;

// Generated Sep 16, 2013 10:14:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * QuestionId generated by hbm2java
 */
public class QuestionId implements java.io.Serializable {

	private Long questionId;
	private String question;

	public QuestionId() {
	}

	public QuestionId(String question) {
		this.question = question;
	}

	public QuestionId(Long questionId, String question) {
		this.questionId = questionId;
		this.question = question;
	}

	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuestionId))
			return false;
		QuestionId castOther = (QuestionId) other;

		return ((this.getQuestionId() == castOther.getQuestionId()) || (this
				.getQuestionId() != null && castOther.getQuestionId() != null && this
				.getQuestionId().equals(castOther.getQuestionId())))
				&& ((this.getQuestion() == castOther.getQuestion()) || (this
						.getQuestion() != null
						&& castOther.getQuestion() != null && this
						.getQuestion().equals(castOther.getQuestion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getQuestionId() == null ? 0 : this.getQuestionId()
						.hashCode());
		result = 37 * result
				+ (getQuestion() == null ? 0 : this.getQuestion().hashCode());
		return result;
	}

}
