package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private long questionId;
	private String question;
	private Integer sequence;

	public Question() {
	}

	public Question(long questionId, String question) {
		this.questionId = questionId;
		this.question = question;
	}

	public Question(long questionId, String question, Integer sequence) {
		this.questionId = questionId;
		this.question = question;
		this.sequence = sequence;
	}

	public long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(long questionId) {
		this.questionId = questionId;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

}
