package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * SystemUser generated by hbm2java
 */
public class SystemUser implements java.io.Serializable {

	private Long userId;
	private String username;
	private String password;
	private String creationDate;
	private String lastUpdatedDate;
	private String userRole;
	private String farmBase;
	private Long loginCount;
	private String createdBy;
	private String question;
	private String answer;

	public SystemUser() {
	}

	public SystemUser(String username, String password, String userRole) {
		this.username = username;
		this.password = password;
		this.userRole = userRole;
	}

	public SystemUser(String username, String password, String creationDate,
			String lastUpdatedDate, String userRole, String farmBase,
			Long loginCount, String createdBy, String question, String answer) {
		this.username = username;
		this.password = password;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.userRole = userRole;
		this.farmBase = farmBase;
		this.loginCount = loginCount;
		this.createdBy = createdBy;
		this.question = question;
		this.answer = answer;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public String getFarmBase() {
		return this.farmBase;
	}

	public void setFarmBase(String farmBase) {
		this.farmBase = farmBase;
	}

	public Long getLoginCount() {
		return this.loginCount;
	}

	public void setLoginCount(Long loginCount) {
		this.loginCount = loginCount;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
